name: oauth
version: 0.4.0
author: Owen Shepherd <*@owenshepherd.net>
description: An implementation of OAuth 1.0a per RFC 5849
homepage: https://github.com/oshepherd/oauth.dart
environment:
    sdk: ">=2.1.0-dev <3.0.0"
dependencies:
  pointycastle: '^1.0.0'
  crypto: '^2.0.1'
  http: '>=0.10.0 <0.12.0'
dev_dependencies:
  shelf: '>=0.6.7+2'
  test: '>=0.10.0'
